Create modules for better performance

diff --git a/kalinethunter b/kalinethunter
--- a/kalinethunter
+++ b/kalinethunter
@@ -1,100 +1,300 @@
-#!/data/data/com.termux/files/usr/bin/bash
-clear
-echo
-DIRECTORY="/data/data/com.termux/files/usr/share/figlet"
-if [ ! -d "$DIRECTORY" ]; then
-apt update && apt install figlet
-fi
-figlet -f mini    .....KALI-NETHUNTER.....
-echo
-echo " ------------Hello This Is Hax4us (devil)-----------"
-echo
-echo
-echo "Select Your Phone Architecture"
-echo "----------------------------------------------------"
-echo "1)arm64/armv8 (64 bit)"
-echo "2)arm/armhf/armv7 (32 bit)"
-echo "3)64 bit minimal version (try this if option 1 is giving errors)"
-echo "4)find your architecture"
-read aarch
-case $aarch in
-1)
-echo
-echo "prerequisites are installing.........."
-echo
-apt install proot wget bsdtar -y
-echo
-echo "installed successfully.... :D"
-echo
-echo "Now Kali Nethunter Is Installing......."
-echo
-wget https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-arm64-full.tar.xz
-echo
-proot --link2symlink bsdtar -xf kalifs-arm64-full.tar.xz
-cd kali-arm64 && echo "nameserver 8.8.8.8" > etc/resolv.conf
+#!/data/data/com.termux/files/usr/bin/bash -e
+# Copyright ©2018 by Hax4Us. All rights reserved.  🌎 🌍 🌏 🌐 🗺
+#
+# https://hax4us.com
+################################################################################
 
-cd .. && echo "unset LD_PRELOAD" > startkali.sh
-printf "proot --link2symlink -0 -r kali-arm64 -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home -b /system -b /mnt /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=$TERM /bin/bash --login" >> startkali.sh
+# colors
 
-chmod 777 startkali.sh && termux-fix-shebang startkali.sh
-echo
-cd $HOME/Nethunter-In-Termux && chmod -R 777 kali-arm64
-echo "Now You Can Start Kali Linux (Nethunter) By :--> ./startkali.sh"
-echo
-;;
-2)
-echo "prerequisites are installing.........."
-echo
-apt install proot wget bsdtar -y
-echo
-echo "installed successfully.... :D"
-echo
-echo "Now Kali Nethunter Is Installing......."
-echo
-wget https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-armhf-minimal.tar.xz
-echo
-proot --link2symlink bsdtar -xf kalifs-armhf-minimal.tar.xz
-cd kali-armhf && echo "nameserver 8.8.8.8" > etc/resolv.conf
-cd .. && echo "unset LD_PRELOAD" > startkali.sh
-printf "proot --link2symlink -0 -r kali-armhf -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home -b /system -b /mnt /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=$TERM /bin/bash --login" >> startkali.sh
+red='\033[1;31m'
+yellow='\033[1;33m'
+blue='\033[1;34m'
+reset='\033[0m'
 
-chmod 777 startkali.sh && termux-fix-shebang startkali.sh
-echo
-echo "Now You Can Start Kali Linux (Nethunter) By :--> ./startkali.sh" 
-echo
-;;
-3)
-echo
-echo "prerequisites are installing.........."
-echo
-apt install proot wget bsdtar -y
-echo
-echo "installed successfully.... :D"
-echo
-echo "Now Kali Nethunter Is Installing......"
-echo
-wget https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-arm64-minimal.tar.xz
-echo
-proot --link2symlink bsdtar -xf kalifs-arm64-minimal.tar.xz
-cd kali-arm64 && echo "nameserver 8.8.8.8" > etc/resolv.conf
+#  url's of all possibls architectures
 
- cd .. && echo "unset LD_PRELOAD" > startkali.sh
-printf "proot --link2symlink -0 -r kali-arm64 -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home -b /system -b /mnt /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=$TERM /bin/bash --login" >> startkali.sh
-chmod 777 startkali.sh && termux-fix-shebang startkali.sh
-echo
-echo "Now You Can Start Kali Linux (Nethunter) By :--> ./startkali.sh"
-echo
-;;
-4)
-echo
-echo "Your phone architecture is :-"
-aarch=`dpkg --print-architecture`
-if [ $aarch = "aarch64" ] ; then
-echo
-echo "bad luck you are using aarch64 so try your luck because it is not personally tested on aarch64..!!"
+urlaarch64="https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-arm64-minimal.tar.xz"
+urlarm="https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-armhf-minimal.tar.xz"
+
+
+# Destination
+
+if [ -d $HOME/kali ]
+	then
+		rm -rf $HOME/kali
+DESTINATION=$HOME/kali
 else
-echo
-echo $aarch
+	DESTINATION=$HOME/TermuxAlpine
+	fi
+cd $DESTINATION
+printrerunerror="Sorry :( to say your downloaded linux file was corrupted or half downloaded but dont worry just rerun my script"
+
+# utility function to initialize arch
+
+getarch() {
+	SETARCH=$1
+}
+
+# Utility function to check integrity
+
+checkintegrity() {
+	integritycheck=PASS
+	echo
+	printf "$blue [*] Checking integrity of file ..."
+	echo
+	echo " [*] Script will be terminate immediately in case of integrity failure"
+	if [ $SETARCH = "aarch64" ]
+		then
+	sha512sum -c kalifs-arm64-minimal.sha512sum && echo || integritycheck=FAIL
+	if [ $integritycheck = "FAIL" ] 
+		then
+			printf "$red $printrerunerror $reset"
+			exit
+		else
+			extract
+		fi
+			elif [ $SETARCH = "armhf" ]
+				then
+		sha512sum -c kalifs-armhf-minimal.sha512sum && echo "" || integritycheck=FAIL
+		if [ $integritycheck = "FAIL" ]
+			then
+				printf"$red $printrerunerror $reset"
+				exit
+			else
+			extract
+				fi
+
+			fi
+}
+
+# Utility function to get tar file
+
+gettarfile() {
+	cd $HOME
+	printf "$blue [*] Getting tar file ...$reset"
+	echo
+	if [ $SETARCH = "aarch64" ]
+		then
+			URL=$urlaarch64	
+		echo
+			curl --progress-bar -L --fail --retry 6 -O "$URL"
+		getsha
+			checkintegrity
+	
+elif [ $SETARCH = "armhf" ]
+		then
+			URL=$urlarm
+		echo
+			curl --progress-bar -L --fail --retry 6 -O "$URL"
+			getsha
+			checkintegrity
 fi
-;;
-esac
+}
+
+# Utility function for Unknown Arch
+
+unknownarch() {
+	printf "$red"
+	echo "[*] Unknown Architecture :("
+	printf "$reset"
+	exit
+}
+
+# Utility function for detect system
+
+checksysinfo() {
+
+	if [ $(getprop ro.product.cpu.abi) = "arm64-v8a" ]
+		then
+			checkdeps
+			getarch aarch64
+			gettarfile
+		elif [ $(getprop ro.product.cpu.abi) = "armeabi" ]; then 
+			checkdeps
+			getarch armhf
+			gettarfile
+		elif [ $(getprop ro.product.cpu.abi) = "armeabi-v7a" ]; then
+    		checkdeps
+			getarch armhf
+			gettarfile
+		else
+			unknownarch
+		fi
+	}
+
+# Utility function for login file
+
+createloginfile() {
+bin=$PREFIX/bin/startkali
+	cat > $bin <<- EOM
+		#!/data/data/com.termux/files/usr/bin/bash -e
+			unset LD_PRELOAD
+				exec proot --link2symlink -0 -r $HOME/kali/ -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b $HOME -w $HOME /usr/bin/env -i HOME=/root TERM="$TERM" LANG=$LANG PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/sh --login
+				EOM
+chmod 700 $bin
+
+}
+
+# Utility function to extract tar file
+
+extract() {
+	printf "$blue [*] Extracting ... $reset"
+	echo
+	if [ $SETARCH = aarch64 ]; then
+		OUTPUT=kalifs-arm64-minimal.tar.gz
+		cd $HOME && proot --link2symlink -0 bsdtar -xpf $OUTPUT 2> /dev/null || : 
+		mv kali-arm64 kali
+
+
+	else
+		OUTPUT=kalifs-armhf-minimal.tar.gz
+               cd $HOME && proot --link2symlink -0 bsdtar -xpf $OUTPUT 2> /dev/null || :
+	       mv kali-armhf kali
+		fi
+createloginfile
+}
+
+checkdeps() {
+	printf "$blue \n"
+	echo " [*] Updating termux ..."
+	apt update -y &> /dev/null
+	echo " [*] Checking all required tools ..."
+	if [ -e $PREFIX/bin/proot ]
+		then
+			echo "  • Proot is OK"
+		else
+			apt install proot -y &> /dev/null
+	if [ ! -e $PREFIX/bin/proot ]
+		then
+			printf "$red \n"
+		echo " ERROR : check your internet connection or apt"
+		printf "\n"
+		echo " Exiting ..."
+		printf "$reset"
+		exit
+		fi
+	
+			fi
+	if [ -e $PREFIX/bin/bsdtar ]
+		then
+			echo "  • Bsdtar is Ok"
+		else
+			apt install bsdtar -y &> /dev/null
+			if [ ! -e $PREFIX/bin/bsdtar ]
+				then
+					printf "$red"
+		echo " ERROR : check your internet connection or apt"
+		echo " [*] Exiting ..."
+		printf "$reset"
+		sleep 1
+		exit
+		fi
+		fi
+	if [ -e $PREFIX/bin/curl ]
+		then
+			echo "  • Curl is OK"
+		else
+			apt install curl -y &> /dev/null
+			if [ ! -e $PREFIX/bin/curl ]
+				then
+	printf "$red"
+	echo " ERROR : check your internet connection or apt "
+
+  echo " Exiting ..."
+  printf "$reset"
+exit
+				fi
+				fi
+}
+
+# Utility function to get SHA
+
+getsha() {
+	echo
+	printf "$blue [*] Getting SHA ... $reset"
+
+	echo
+	echo
+	if [ $SETARCH = "aarch64" ]
+		then
+		curl --progress-bar -L --fail --retry 4 -O https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-arm64-minimal.sha512sum
+	elif [ $SETARCH = "armhf" ]
+		then
+	curl --progress-bar -L --fail --retry 4 -O https://build.nethunter.com/kalifs/kalifs-20171013/kalifs-armhf-minimal.sha512sum
+	else 
+		printf "$red Your phone is supported but cant download SHA file plz contact to lokesh@hax4us.com $reset"
+		exit
+	fi
+
+}
+
+# Utility function to touchup (under construction)
+
+#finalwork() {
+#	if [ ! -e $HOME/finaltouchup.sh ] 
+#		then
+#	
+#	curl -LO https://raw.githubusercontent.com/Hax4us/TermuxAlpine/master/finaltouchup.sh
+#	. finaltouchup.sh
+#else
+#	. finaltouchup.sh
+#	fi
+#}
+
+# Utility function for cleanup
+
+#cleanup() {
+#	if [ -d $DESTINATION ]
+#		then
+#	rm -rf $DESTINATION
+#else
+#	printf "$red not installed so not removed"
+#	echo
+#	fi
+#	if [ -e $PREFIX/bin/startalpine ]
+#		then
+#	rm $PREFIX/bin/startalpine
+#	printf "$yellow uninstalled :) $reset"
+#	echo
+#else
+#	printf "$red not installed so not removed $reset"
+#	echo
+#	fi
+
+#}
+
+# Start
+clear
+#EXTRAARGS="default"
+#if [[ ! -z $1 ]]
+#	then
+#EXTRAARGS=$1
+#if [[ $EXTRAARGS = "uninstall" ]]
+#	then
+#		cleanup
+#		exit
+#		fi
+#		fi
+echo
+printf "$yellow You are going to install Kali Nethunter in termux ;) Cool"
+echo
+echo
+echo
+printf "$blue [*] Checking host architecture ..."
+checksysinfo
+printf "$blue [*] Configuring Nethunter For You ..."
+cd $HOME && finalwork
+printf "$blue"
+echo
+echo
+echo " #-----------------------------------------------#"
+echo
+printf "$blue [∆] My Official Mail : $yellow lokesh@hax4us.com"
+echo
+printf "$blue [∆] My Website       : $yellow https://hax4us.com"
+echo
+printf "$blue [∆] My Channel       : $yellow https://youtube.com/hax4us $reset"
+printf "$blue"
+echo
+echo " #-----------------------------------------------#"
+printf "$reset"
